### ISSUE TITLE
[FE] 말하고 있는 사용자(발화자)를 표시한다.

### ISSUE THREAD

**Issue by studioOwol** [boostcampwm-2024/web19-Clovapatra#154]

**Comment by dev-taewon-kim** [comment]
[usePitchStore의 currentVolume 활용하시면 될 것 같습니다](https://github.com/boostcampwm-2024/web19-Clovapatra/pull/174/commits/ddb5d783e310e5e5c859695af0a7a4bb108fc3de#diff-ced5875e9bcb0a982bd9c236b402700fef3733f7dc1d2366b27f54bb59d26975R8)
